remote_theme: zendesk/jekyll-theme-zendesk-garden@v0.7.3
search_enabled: true
sidebar:
  - home
  - user-guide
  - references
  - tools
  - performance
  - extra
markdown: kramdown
title: SLEEF Vectorized Math Library
logo: img/sleeflogo3.png
description: Vectorized C99 math functions across popular platforms and architectures.

