plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
markdown: kramdown
title: SLEEF Vectorized Math Library
description: Vectorized C99 math functions across popular platforms and architectures.
logo: sleeflogo3.png
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
