plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
markdown: kramdown
title: SLEEF Vectorized Math Library
logo: sleeflogo3.png
description: Add a short description here?
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
